# Generated by Django 3.1.4 on 2023-07-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
